// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkNmBP1FgJNUnGSKeCmOEGGOCT1nPiHjE',
    appId: '1:289872853637:web:9c3c30ad2f815eb05bc7ec',
    messagingSenderId: '289872853637',
    projectId: 'goouts-f16db',
    authDomain: 'goouts-f16db.firebaseapp.com',
    storageBucket: 'goouts-f16db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0u_n7kV2uPuSKFjaqYOyEiioDR5Y5d9o',
    appId: '1:289872853637:ios:6061ccf0dec984b75bc7ec',
    messagingSenderId: '289872853637',
    projectId: 'goouts-f16db',
    storageBucket: 'goouts-f16db.firebasestorage.app',
    // CLIENT_ID from GoogleService-Info.plist — REQUIRED for Firebase Phone
    // Auth reCAPTCHA fallback on iOS. Without it the native SDK throws an
    // NSException (instant crash) when verifyPhoneNumber falls back to web
    // verification, because it cannot resolve the registered URL scheme.
    iosClientId:
        '289872853637-hsn5qkb1g7fehvdelmc1rh18c847fame.apps.googleusercontent.com',
    iosBundleId: 'com.goouts.driver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0u_n7kV2uPuSKFjaqYOyEiioDR5Y5d9o',
    appId: '1:289872853637:ios:6061ccf0dec984b75bc7ec',
    messagingSenderId: '289872853637',
    projectId: 'goouts-f16db',
    storageBucket: 'goouts-f16db.firebasestorage.app',
    iosBundleId: 'com.goouts.driver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkNmBP1FgJNUnGSKeCmOEGGOCT1nPiHjE',
    appId: '1:289872853637:web:7461195d14c1f92b5bc7ec',
    messagingSenderId: '289872853637',
    projectId: 'goouts-f16db',
    authDomain: 'goouts-f16db.firebaseapp.com',
    storageBucket: 'goouts-f16db.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8x5e2Qbm5ccOHnSc4RJpLNQ57Bo3y0sk',
    appId: '1:289872853637:android:5b74a316b276c2715bc7ec',
    messagingSenderId: '289872853637',
    projectId: 'goouts-f16db',
    storageBucket: 'goouts-f16db.firebasestorage.app',
  );

}